"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var RetiermentAccount_1 = require("./RetiermentAccount");
var SavingsAccount_1 = require("./SavingsAccount");
var CheckingAccount_1 = require("./CheckingAccount");
var checking = new CheckingAccount_1.CheckingAccount();
var savings = new SavingsAccount_1.SavingsAccount();
var Retierment = new RetiermentAccount_1.RetiermentAccount();
console.log(savings.withdrawMoney(400, "Shoes", 2));
console.log(savings.success);
console.log(savings.errorMessage);
console.log(savings.transactionDate);
console.log(savings.balance);
console.log(savings.description);
console.log(savings.monthlyTransactions);
console.log(checking.withdrawMoney(200, "nails", 1));
console.log(checking.success);
console.log(checking.errorMessage);
console.log(checking.transactionDate);
console.log(checking.balance);
console.log(checking.description);
console.log(Retierment.withdrawMoney(4000, "makeup", 2));
console.log(Retierment.success);
console.log(Retierment.errorMessage);
console.log(Retierment.transactionDate);
console.log(Retierment.balance);
console.log(Retierment.description);
console.log(Retierment.monthlyTransactions);
